###############################################################################################
#
# [Required] Provide input to GETA_Snakemake
#
###############################################################################################

Input:
  RM_species:             # Species identifier for RepeatMasker. (e.g. Embryophyta)
  genome:                 # Genome file in fasta format.
  rnaseq_single:          # RNAseq single-end data (fastq.gz). Comma separated file list
                          # **Note** All RNAseq data (paired and single) must be in same directory
  rnaseq_first:           # RNAseq paired-end data, read 1(*_1.fq.gz). Comma separated file names                     # (paired) or single end sequencing data
  rnaseq_second:          # RNAseq paired-end data, read 2(*_2.fq.gz). Comma separated file names
  protein:                # Homologous protein sequences (recommended from multiple species) fasta file.
  AUGUSTUS_CONFIG_PATH:   # Path to Augustus configuration directory 
  augustus_species:       # Species identifier for Augustus. The relative hmm files of augustus 
                          # training will be created with this prefix. If the relative hmm files 
                          # of augustus training exists, the program will delete the hmm files 
                          # directory first, and then start the augustus training steps.
  use_augustus:           # Species identifier for Augustus. This parameter conflicts with 
                          # augustus_species. When this parameter set, the augustus_species 
                          # parameter will be invalid, and the relative hmm files of augustus 
                          # training must exist, and the augustus training step will be skipped 
                          # (this will save lots of running time).

###############################################################################################
#
# [Optional] Provide additional input
#
###############################################################################################

  out_prefix: getaOut     # Prefix for output files
  RM_lib: None            # A fasta file of repeat sequences. Generally the result of 
                          # RepeatModeler. If not set, RepeatModeler will be used for producing 
                          # this file automaticly, which is time intensive.
  strand_specific: False  # Enable the ability of analysing the strand-specific information 
                          # provided by the tag "XS" from SAM format alignments.
  pfam_db: None           # The absolute path of Pfam database which was used for filtering of 
                          # false positive gene models.
  gene_prefix: gene       # The prefix of gene id shown in output file.
  enable_augustus_training_iteration: False

###############################################################################################
#
# [Required] Cluster processing parameters (Memory and multithreading) 
#
###############################################################################################

Threads:
  RepeatMasker_species: 4
  RepeatModeler: 4
  RepeatMasker_custom: 4
  RepeatMasker_merge: 4
  TrimGalore_paired: 4
  TrimGalore_single: 4
  HiSat2: 4

__DEFAULT__:
  account: cpu-s1-pgl-0         # Provide cluster account
  partition": cpu-s1-pgl-0      # Provide cluster partition
  memory: 16g
  name: JOBNAME.{rule}.{wildcards}
  ncpus": 1
  nodes": 1
  time": 7-00:00:00
  output": logs/{rule}.{wildcards}.out
  error": logs/{rule}.{wildcards}.err
RepeatMasker_species: 
  ncpus: 16
  memory: 64g
RepeatModeler:
  ncpus: 16
  memory: 64g
RepeatMasker_custom:
  ncpus: 16
  memory: 64g
RepeatMasker_merge:
  ncpus: 16
  memory: 64g
TrimGalore_paired:
  ncpus: 16
  memory: 64g
TrimGalore_single:
  ncpus: 16
  memory: 64g
HiSat2_build:
  ncpus: 16
  memory: 64g
HiSat2:
  ncpus: 16
  memory: 64g
HiSat2_sort:
  ncpus: 16
  memory: 64g

###############################################################################################
#
# [Careful!] Arguments for internal processing. Edit with caution
#
###############################################################################################

Internal:
  RepeatMasker: -e ncbi -gff
  TrimGalore: 
  hisat2-build: -p 1
  hisat2: --min-intronlen 20 --max-intronlen 20000 --dta --score-min L,0.0,-0.4
  sam2transfrag: --fraction 0.05 --min_expressed_base_depth 2 --max_expressed_base_depth 50 --min_junction_depth 2 --max_junction_depth 50 --min_fragment_count_per_transfrags 10 --min_intron_length 20
  TransDecoder.LongOrfs: -m 100 -G universal
  TransDecoder.Predict: --retain_long_orfs_mode dynamic
  homolog_genewise: --coverage_ratio 0.4 --evalue 1e-9
  homolog_genewiseGFF2GFF3: --min_score 15 --gene_prefix genewise --filterMiddleStopCodon
  geneModels2AugusutsTrainingInput: --min_evalue 1e-9 --min_identity 0.8 --min_coverage_ratio 0.8 --min_cds_num 2 --min_cds_length 450 --min_cds_exon_ratio 0.60
  BGM2AT: --min_gene_number_for_augustus_training 500 --gene_number_for_accuracy_detection 200 --min_gene_number_of_optimize_augustus_chunk 50 --max_gene_number_of_optimize_augustus_chunk 200
  prepareAugusutusHints: --margin 20
  paraAugusutusWithHints: --gene_prefix augustus --min_intron_len 20 --alternatives_from_evidence
  paraCombineGeneModels: --overlap 30 --min_augustus_transcriptSupport_percentage 10.0 --min_augustus_intronSupport_number 1 --min_augustus_intronSupport_ratio 0.01
  PfamValidateABinitio: --CDS_length 750 --CDS_num 2 --evalue 1e-5 --coverage 0.25
  remove_genes_in_repeats: --ratio 0.8
  remove_short_genes: --cds_length 150